language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  fast_finish: true

env:
  global:
    # add composer's global bin directory to the path
    # see: https://github.com/drush-ops/drush#install---composer
    - PATH="$PATH:$HOME/.composer/vendor/bin"

script:
  - cd ./tests
  - ./run-tests.sh
  - ./run-coverage.sh
  - cd ..

after_script:
  - cd ./tests
  - php vendor/bin/coveralls


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c2147c4ed13ddd031b30
      - https://webhooks.gitter.im/e/45a8fac3fb8fd2ae907d
    on_success: change
    on_failure: always
    on_start: false
